SetOfSequencesChem can contain interacting molecules (for conplex)
scipion-chem/scipion-chem pull request #89
Opened 2023-12-14 17:56 UTC by DaniDelHoyo

Features added to SetOfSequencesChem
New wizard for multiElement selection

2023-12-18 15:09 UTC, MartinSalinas98 requested changes

2023-12-18 15:09 UTC, martin-s-a commented on pwchem/objects/base.py
> +        return '/'.join(self.getSetPath().split('/')[:-1])
better with:
```py
os.path.dirname(self.getSetPath())
```

2023-12-18 15:09 UTC, martin-s-a commented on pwchem/protocols/VirtualDrugScreening/protocol_extract_interactingMols.py
> +    _, _, molNames = getFilteredOutput(inSeqs, filtSeqNames, filtMolNames, self.scThres.get())
maybe:
```py
molNames = getFilteredOutput(inSeqs, filtSeqNames, filtMolNames, self.scThres.get())[-1]
```
?
It's not better or worse, just personal preference

2023-12-18 15:09 UTC, martin-s-a commented on pwchem/viewers/viewers_sequences.py
> +            return os.path.abspath(self.getProject().getTmpPath())
Better:
```py
def getOutDir(self):
        return os.path.abspath(self.getProtocol()._getExtraPath() if self.getProtocol() else self.getProject().getTmpPath())
```

2023-12-19 11:07 UTC, DaniDelHoyo commented on pwchem/protocols/VirtualDrugScreening/protocol_extract_interactingMols.py
> +    _, _, molNames = getFilteredOutput(inSeqs, filtSeqNames, filtMolNames, self.scThres.get())
lloron

2023-12-19 11:07 UTC, MartinSalinas98 commented on pwchem/protocols/VirtualDrugScreening/protocol_extract_interactingMols.py
> +    _, _, molNames = getFilteredOutput(inSeqs, filtSeqNames, filtMolNames, self.scThres.get())
sí

2023-12-19 11:57 UTC, MartinSalinas98 approved these changes

2023-12-19 12:02 UTC, merged